// action Types
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const VOTE_MOVIE = 'VOTE_MOVIE';
export const SUBMITTING_RATINGS = 'SUBITTING_RATINGS';
export const SUBMIT_RATINGS_SUCCESS = 'SUBMIT_RATINGS_SUCCESS';
export const SUBMIT_RATINGS_ERROR = 'SUBMIT_RATINGS_ERROR';
export const FETCH_RECOMMENDATIONS = 'FETCH_RECOMMENDATIONS';
export const FETCH_RECOMMENDATIONS_SUCCESS = 'FETCH_RECOMMENDATIONS_SUCCESS';
